---
- include: merge_vars.yml
  tags:
    - always

- name: Create prometheus data directory
  file:
    path: "{{ prometheus.data_dir }}"
    state: directory
    owner: "{{ prometheus.user_id }}"

- name: Write config file
  template:
    src: prometheus.yml
    dest: "{{ prometheus.data_dir }}/"
    owner: "{{ prometheus.user_id }}"
  notify: Service handler

- include: setup_container.yml
  when: containerized

- import_tasks: install_packages.yml
  when: not containerized
