---
defaults:
  prometheus:
    container_name: prom/prometheus
    version: latest
    data_dir: /var/lib/cephmetrics
    user_id: '65534'  # This is the UID used by the prom/prometheus docker image
