---
- name: Restart Grafana
  service:
    name: grafana-server
    state: restarted
    enabled: true

- name: Restart graphite-web
  service:
    # graphite-web is served by httpd
    name: httpd
    state: restarted
    enabled: true

- name: Restart carbon-cache
  service:
    name: carbon-cache
    state: restarted
    enabled: true
