---
containerized_deployment: false
use_epel: false
devel_mode: true
replace_dashboards: true
graphite:
  port: "{{ graphite_port | default('8080') }}"
  user: admin
  password: admin
  grafana_name: Local
# The firewalld zone that carbon and grafana will use
firewalld_zone: public
# RHEL repos that need to be enabled with subscription-manager
rhsm_repos:
  - rhel-7-server-rhscon-2-installer-rpms
  - rhel-7-server-optional-rpms
devel_packages:
  yum:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - graphite-web
    - python-carbon
    - grafana
  apt:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - python-yaml
    - python-requests
