---
defaults:
  # graphite defaults are now in the cephmetrics-common role since the
  # ceph-collectd role needs access to them
  replace_dashboards: true
  update_alerts: false
  grafana:
    containerized: false
    datasource: Local
    # Note: changing this value won't update the password in Grafana itself;
    # change it via the web UI and then override this value to reflect.
    user: admin
    admin_password: admin
    plugins:
      - vonage-status-panel
      - grafana-piechart-panel
