---
containerized_deployment: false
use_epel: false
devel_mode: true
replace_dashboards: true
graphite:
  port: "{{ graphite_port | default('8080') }}"
  user: admin
  password: admin
  grafana_name: Local
# The firewalld zone that carbon and grafana will use
firewalld_zone: public
