---
defaults:
  grafana:
    container_name: "grafana/grafana"
    container_tag: latest
    container_cpu_period: 100000
    container_cpu_cores: 2
    # container_memory is in GB
    container_memory: 4
    uid: 472
    datasource: Dashboard
    dashboards_path: "/etc/grafana/dashboards/ceph-dashboard"
    plugins:
      - vonage-status-panel
      - grafana-piechart-panel
  dashboard:
    admin_user: admin
    admin_password: admin
    rgw_api_user_id: ceph-dashboard
    rgw_api_host: ''
    rgw_api_port: ''
    rgw_api_scheme: ''
    rgw_api_admin_resource: ''
    rgw_api_no_ssl_verify: ''
devel_packages:
  yum:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - PyYAML
    - python-requests
  apt:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - grafana
    # for dashUpdater.py
    - python-yaml
    - python-requests
