---
- name: Configure retention for collectd stats
  blockinfile:
    dest: /etc/carbon/storage-schemas.conf
    # NOTE: Retention settings are applied to metrics as they are *created*. If
    # these settings are changed after-the-fact, it's necessary to either
    # delete the whisper files (!) or run whisper-resize on them all.
    block: |
      [collectd]
      pattern = ^collectd\.
      retentions = 1s:7d,1m:30d,15m:5y
    # This must be above other declarations in the file
    insertbefore: "BOF"
  notify: Restart carbon-cache
