---
- name: Check firewalld status
  shell: "systemctl show firewalld | grep UnitFileState"
  register: firewalld_status

- name: Open port 3000 for Grafana
  firewalld:
    port: 3000/tcp
    zone: public
    state: enabled
    immediate: true
    permanent: true
  when: "'enabled' in firewalld_status.stdout"
