---
- set_fact:
    # Changing collectd_interval is not supported at this time
    whisper_retention: "{{ collectd_interval|default('10') }}s:7d,1m:30d,15m:5y"

- name: Configure retention for collectd stats
  template:
    src: storage-schemas.conf
    dest: /etc/carbon/storage-schemas.conf
  notify:
    - Resize whisper databases
    - Restart carbon-cache

- name: Ensure /var/lib/carbon has the right ownership
  file:
    path: /var/lib/carbon
    state: directory
    owner: carbon
    group: carbon
    recurse: yes
  notify:
    - Restart carbon-cache
