---
- name: Set WHISPER_AUTOFLUSH to True
  lineinfile:
    dest: /etc/carbon/carbon.conf
    regexp: "^WHISPER_AUTOFLUSH = .*"
    insertafter: "^#.*buffering writes from the kernel.*"
    line: "WHISPER_AUTOFLUSH = True"
  notify:
    - Restart carbon-cache

- name: Set whisper_retention
  set_fact:
    # Changing collectd_interval is not supported at this time
    whisper_retention: "{{ collectd_interval|default('10') }}s:7d,1m:30d,15m:5y"

- name: Configure retention for collectd stats
  template:
    src: storage-schemas.conf
    dest: /etc/carbon/storage-schemas.conf
  notify:
    - Resize whisper databases
    - Restart carbon-cache

- name: Ensure carbon storage has the right ownership
  file:
    path: "{{ carbon.storage_dir[ansible_pkg_mgr] }}"
    state: directory
    owner: "{{ carbon.unix_user[ansible_pkg_mgr] }}"
    group: "{{ carbon.unix_user[ansible_pkg_mgr] }}"
    recurse: yes
  notify:
    - Restart carbon-cache
