---
- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - graphite-web
    - python-carbon
    - grafana
  when: devel_mode

- name: Install cephmetrics
  package:
    name: cephmetrics
    state: latest
  when: not devel_mode
