---
- name: Install packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    # unzip is needed to extract the Vonage plugin
    - unzip
    - graphite-web
    - python-carbon
    - grafana
