---
- yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_pkg_mgr == "yum"

- name: Add Grafana repo
  template:
    src: grafana.repo
    dest: /etc/yum.repos.d/grafana.repo
  when: ansible_pkg_mgr == "yum"

- name: Install packages
  package: 
    name: "{{ item }}"
    state: latest
  with_items:
    - graphite-api
    - graphite-web
    - python-carbon
    - grafana
