---
- include: merge_vars.yml

- include: setup_container.yml
  when:
    - containerized

- include: install_packages.yml
  when:
    - not containerized

- include: configure_firewall.yml

- include: configure_grafana.yml
