---
- include: install_packages.yml
  when: not containerized_deployment
  tags:
    - packages

- include: configure_graphite.yml
  when: not containerized_deployment
  tags:
    - graphite

- include: configure_grafana.yml
  when: not containerized_deployment
  tags:
    - grafana

- include: start_services.yml
  when: not containerized_deployment
  tags:
    - services
