---
- name: Enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - carbon-cache
    # graphite-web is served by httpd
    - httpd
    - grafana-server
