---
- name: Enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - carbon-cache
    # graphite-web is served by httpd
    - "{{ 'httpd' if graphite.service == 'graphite-web' else graphite.service }}"
    - grafana-server
