---
- name: Set collectd_dir
  set_fact:
    collectd_dir: "/usr/lib{{ '64' if ansible_pkg_mgr == 'yum' else '' }}/collectd"

- name: Set collectors_dir
  set_fact:
    collectors_dir: "{{ collectd_dir }}/cephmetrics_collectors"

- name: Remove stale Python files
  file:
    dest: "{{ item }}"
    state: absent
  with_items:
    - "{{ collectd_dir }}/cephmetrics"

- name: Ship collectors
  synchronize:
    src: files/cephmetrics_collectors/
    dest: "{{ collectors_dir }}"
    delete: yes
    rsync_opts:
      - "--exclude=*.pyc"
      - "--exclude=__pycache__"
      - "--delete-excluded"
  notify: Restart collectd

- name: Ship collectd plugin
  copy:
    src: files/cephmetrics.py
    dest: "{{ collectd_dir }}"
  notify: Restart collectd
