---
- set_fact:
    collectors_dir: /usr/lib64/collectd/python-plugins/collectors

- name: Create collectors directory
  file:
    name: "{{ collectors_dir }}"
    state: directory

- name: Ship collector plugins
  copy:
    src: files/collectors/
    dest: "{{ collectors_dir }}"
  notify: Restart collectd

- name: Ship cephmetrics.py
  copy:
    src: files/cephmetrics.py
    dest: /usr/lib64/collectd/python-plugins/
  notify: Restart collectd
