---
- set_fact:
    collectors_dir: /usr/lib64/collectd/python-plugins/collectors

- set_fact:
    repo_relpath: "../../../"

- name: Create collectors directory
  file:
    name: "{{ collectors_dir }}"
    state: directory

- name: Ship collector plugins
  copy:
    src: "{{ repo_relpath }}/collectors/"
    dest: "{{ collectors_dir }}"

- name: Ship cephmetrics.py
  copy:
    src: "{{ repo_relpath }}/cephmetrics.py"
    dest: /usr/lib64/collectd/python-plugins/

- name: Ship collectd.conf
  copy:
    src: "{{ repo_relpath }}/etc/collectd.conf"
    dest: /etc/

- name: Ship /etc/collectd.d
  copy:
    src: "{{ repo_relpath }}/etc/collectd.d"
    dest: /etc/

- name: Set hostname in write_graphite.conf
  replace:
    path: "/etc/collectd.d/write_graphite.conf"
    regexp: 'Host ".*"'
    replace: "Host \"{{ groups['ceph-grafana'][0] }}\""

- name: Set cluster name in cephmetrics.conf
  replace:
    path: /etc/collectd.d/cephmetrics.conf
    regexp: 'ClusterName ".*"'
    replace: 'ClusterName "{{ cluster }}"'
