---
- yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  when: ansible_pkg_mgr == "yum"

- package:
    name: collectd
    state: latest
