---
- name: Install collectd
  package:
    name: collectd
    state: latest
  when:
    - devel_mode
  notify: Restart collectd

- name: Install collectd-python
  package:
    name: collectd-python
    state: latest
  when:
    - ansible_pkg_mgr == "yum"
    - devel_mode
    - not use_epel
  notify: Restart collectd

- name: Install cephmetrics-collectors
  package:
    name: cephmetrics-collectors
    state: latest
  when:
    - ansible_pkg_mgr == "yum"
    - not devel_mode
  notify: Restart collectd

- name: Install dependencies for collector plugins
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    # For the json python module
    - python-libs
    # For the rados python module
    - python-rados
    # For the ceph_daemon python module
    - ceph-common
  when:
    - ansible_pkg_mgr == "yum"
    - devel_mode
  notify: Restart collectd
