---
- set_fact:
    collectd_dir: /usr/lib64/collectd/cephmetrics

- name: Create collectors directory
  file:
    name: "{{ collectd_dir }}/collectors"
    state: directory

- name: Ship collector plugins
  copy:
    src: files/collectors/
    dest: "{{ collectd_dir }}/collectors"
  notify: Restart collectd

- name: Ship cephmetrics.py
  copy:
    src: files/cephmetrics.py
    dest: "{{ collectd_dir }}"
  notify: Restart collectd
