---
- set_fact:
    collectors_dir: /usr/lib64/collectd/python-plugins/collectors

- name: Create collectors directory
  file:
    name: "{{ collectors_dir }}"
    state: directory

- name: Ship collector plugins
  copy:
    src: files/collectors/
    dest: "{{ collectors_dir }}"
  notify: Restart collectd

- name: Ship cephmetrics.py
  copy:
    src: files/cephmetrics.py
    dest: /usr/lib64/collectd/python-plugins/
  notify: Restart collectd

- name: Ship collectd.conf
  copy:
    src: files/etc/collectd.conf
    dest: /etc/
  notify: Restart collectd

- name: Ship /etc/collectd.d
  copy:
    src: files/etc/collectd.d
    dest: /etc/
  notify: Restart collectd

- name: Set hostname in write_graphite.conf
  replace:
    dest: "/etc/collectd.d/write_graphite.conf"
    regexp: 'Host ".*"'
    replace: "Host \"{{ groups['ceph-grafana'][0] }}\""
  notify: Restart collectd

- name: Set cluster name in cephmetrics.conf
  replace:
    dest: /etc/collectd.d/cephmetrics.conf
    regexp: 'ClusterName ".*"'
    replace: 'ClusterName "{{ cluster }}"'
  notify: Restart collectd
