---
- include: merge_vars.yml
  tags:
    - always

- name: Skip if not configured
  meta: end_play
  when: backend.metrics != 'cephmetrics'

- include: setup_repos.yml
  when:
    - not containerized_deployment
  tags:
    - packages
    - repos

- include: install_packages.yml
  when: not containerized_deployment
  tags:
    - packages

- include: set_collectd_vars.yml
  tags:
    - collectors

- include: install_collectd_plugins.yml
  when:
    - not containerized_deployment
    - devel_mode
  tags:
    - collectors

- include: configure_collectd.yml
  when: not containerized_deployment
  tags:
    - collectors

- include: selinux.yml
  when:
   - not containerized_deployment
   - ansible_pkg_mgr == "yum"
   - ansible_selinux.status is defined
   - ansible_selinux.status == 'enabled'
  tags:
    - selinux

- include: start_collectd.yml
  when: not containerized_deployment
  tags:
    - services
