---
- include: install_packages.yml
  when: not containerized_deployment
  tags:
    - packages

- include: install_collectd_plugins.yml
  when: not containerized_deployment
  tags:
    - collectors

- include: start_collectd.yml
  when: not containerized_deployment
  tags:
    - services
