---
- name: Enable collectd_tcp_network_connect SELinux boolean
  seboolean:
    name: collectd_tcp_network_connect
    state: yes
    persistent: yes

- include: selinux_module.yml
  when:
    - devel_mode
