---
- name: Enable EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: "{{ 'present' if use_epel else 'absent' }}"
  when:
    - ansible_pkg_mgr == "yum"
    - devel_mode

- name: Install cephmetrics development repo
  copy:
    src: cephmetrics-devel.repo
    dest: /etc/yum.repos.d/cephmetrics.repo
  when:
    - ansible_pkg_mgr == "yum"
    - devel_mode

- name: Remove cephmetrics development repo
  file:
    path: /etc/yum.repos.d/cephmetrics.repo
    state: absent
  when:
    - ansible_pkg_mgr == "yum"
    - use_epel
    - devel_mode

- name: Install cephmetrics production repo
  copy:
    src: files/cephmetrics-prod.repo
    dest: /etc/yum.repos.d/cephmetrics.repo
  when:
    - ansible_pkg_mgr == "yum"
    - not devel_mode
