global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ceph'
    honor_labels: true
    static_configs:
{% for host in groups['mgrs'] %}
      - targets: ['{{ host }}:9283']
        labels:
          instance: 'ceph_cluster'
{% endfor %}
