---
defaults:
  containerized: true
  devel_mode: true
  # The firewalld zone that carbon and grafana will use
  firewalld_zone: public
  # Choose http or https
  # For https, you should set grafana.crt/key and dashboard.crt/key
  protocol: http
  # We need this for both grafana and the mgr-dashboard module
  grafana:
    # You need to change these in the web UI on an already deployed machine, first
    # New deployments work fine
    admin_user: admin
    admin_password: admin
    # We only need this for SSL (https) connections
    crt: ''
    key: ''
  dashboard:
    # We only need this for SSL (https) connections
    crt: ''
    key: ''
    port: 8234
