global:
  scrape_interval: 10s # By default, scrape targets every 15 seconds.
  evaluation_interval: 10s # By default, scrape targets every 15 seconds.

rule_files:

scrape_configs:
- job_name: cephmetrics
  scrape_interval: 5s
  static_configs:
  - targets: [{% for host in ceph_collectd %}'{{ host }}:9103', {% endfor %}]
