---
- hosts: all
  gather_facts: true
  any_errors_fatal: true

- hosts:
  - mgrs
  become: true
  tasks:
    - name: Restart ceph-mgr services to make sure they are properly loaded
      shell: |
        systemctl restart ceph-mgr*.service

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-mgr

- hosts:
  - ceph-dashboard
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  - iscsis
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-node-exporter

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Generate a preliminary Self Signed OpenSSL certificate for grafana and dashboard
      shell: |
        test -f /tmp/ceph-dashboard.key -a -f /tmp/ceph-dashboard.crt || \
        openssl req -new -nodes -x509 -subj '/O=IT/CN=ceph-dashboard' -days 3650 -keyout /tmp/ceph-dashboard.key -out /tmp/ceph-dashboard.crt -extensions v3_ca

- hosts:
  - ceph-dashboard
  become: true
  roles:
  - ceph-prometheus
  - ceph-dashboard
