---
- hosts:
  - ceph-grafana
  become: true
  vars:
    - ceph_collectd: "{{ ((groups['mons']       | default([])) +
                          (groups['agents']     | default([])) +
                          (groups['osds']       | default([])) +
                          (groups['mdss']       | default([])) +
                          (groups['rgws']       | default([])) +
                          (groups['nfss']       | default([])) +
                          (groups['restapis']   | default([])) +
                          (groups['rbdmirrors'] | default([])) +
                          (groups['clients']    | default([])) +
                          (groups['mgrs']       | default([])) +
                          (groups['cluster']    | default([]))) | unique }}"
  roles:
  - ceph-grafana

- hosts:
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-collectd

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print dashboard URL
      debug:
        msg: "All done! You may access your dashboard at http://{{ groups['ceph-grafana'][0] }}:3000/ with user 'admin' and password 'admin'. Note that initially the dashboard will be incomplete; after a few minutes it should have enough data collected to function properly."
