---
- hosts: all
  gather_facts: true
  any_errors_fatal: true

- hosts:
  - mgrs
  become: true
  tasks:
    - name: Restart ceph-mgr services to make sure they are properly loaded
      shell: |
        systemctl restart ceph-mgr*.service

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-mgr

- hosts:
  - ceph-grafana
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  - iscsigws
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-node-exporter

- hosts:
  - ceph-grafana
  become: true
  roles:
  - ceph-prometheus
  - ceph-grafana

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-dashboard
