---
- hosts:
  - ceph-grafana
  become: true
  roles:
  - ceph-grafana

- hosts:
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-collectd

- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Print dashboard URL
      debug:
        msg: "All done! You may access your dashboard at http://{{ groups['ceph-grafana'][0] }}:3000/ with user 'admin' and password 'admin'."
