---
- hosts: all
  gather_facts: true
  any_errors_fatal: true

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-mgr

- hosts:
  - ceph-dashboard
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  - iscsis
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-node-exporter

- hosts:
  - ceph-dashboard
  become: true
  roles:
  - ceph-prometheus
  - ceph-dashboard

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print dashboard URL
      debug:
        msg: "All done! You may access your dashboard at http://{{ groups['ceph-dashboard'][0] }}:<port>/ (default port is 8004) with your pre-defined username and password (admin/admin by default)."
