---
- hosts: all
  gather_facts: true
  any_errors_fatal: true

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-mgr-prometheus

- hosts:
  - ceph-grafana
  become: true
  roles:
  - ceph-prometheus

- hosts:
  - ceph-grafana
  # These are roles used by ceph-ansible
  - mons
  - agents
  - osds
  - mdss
  - rgws
  - nfss
  - restapis
  - rbdmirrors
  - clients
  - mgrs
  - iscsis
  # This role is (so far) only used for testing
  - cluster
  become: true
  roles:
  - ceph-node-exporter

- hosts:
  - ceph-grafana
  become: true
  roles:
  - ceph-grafana

- hosts:
  - mgrs[0]
  become: true
  roles:
  - ceph-mgr-dashboard

- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Print dashboard URL
      debug:
        msg: "All done! You may access your dashboard at http://{{ groups['ceph-grafana'][0] }}:8080/ with your pre-defined user and password (admin/admin by default)."
