---
defaults:
  node_exporter:
    arch_map:
      x86_64: amd64
      i386: '386'
    packages:
      - prometheus-node-exporter
    service_name: node_exporter
    container_image: prom/node-exporter:latest
