---
- include: merge_vars.yml

- name: Check firewalld status
  shell: "systemctl show firewalld | grep UnitFileState"
  register: firewalld_status
  failed_when: false
  changed_when: false

- name: Open ports for Ceph Manager plugins
  firewalld:
    port: "{{ item }}"
    zone: "{{ firewalld_zone }}"
    state: enabled
    immediate: true
    permanent: true
  with_items:
    - 9283/tcp
    - "{{ dashboard.port }}/tcp"
  when: "'enabled' in firewalld_status.stdout"

- name: Check to see if the mgr is containerized
  command: "docker inspect {{ item }}"
  with_items:
    - "ceph-mgr@{{ ansible_hostname }}"
    - "ceph-mgr-{{ ansible_hostname }}"
  register: mgr_container
  failed_when: false

- name: Choose the correct container name
  set_fact:
    container_name: "{% for res in mgr_container.results if res.rc == 0 %}{{ res.item }}{% endfor %}"
    mgr_prefix: "" # Set the default value for mgr_prefix

- name: Prefix the mgr command with a docker command
  set_fact:
    mgr_prefix: "docker exec {{ container_name }}"
  when: container_name != ""

- name: Enable mgr prometheus module
  command: "{{ mgr_prefix }} ceph mgr module enable prometheus"

- name: Enable mgr dashboard module
  command: "{{ mgr_prefix }} ceph mgr module enable dashboard"
